language: perl
perl:
  - "5.24"
  - "5.26"
before_install:
  - cpanm --notest --quiet Dist::Zilla
  - dzil authordeps | cpanm --notest --quiet
  - cpanm --notest --quiet Pod::Coverage::TrustPod

install:
  # Git always asks me to run this... :-p
  - git config --global user.name 'you@example.com'
  - git config --global user.name 'Your Name'

  - dzil listdeps | cpanm --notest --quiet
script:
  - dzil test --release --verbose
